services:
  app:
    build: .
    container_name: payment_app
    restart: unless-stopped
    ports:
      - "9443:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
